---
geometry: margin=1in
fontsize: 12pt

header-includes:
 - \usepackage{setspace}
 - \usepackage{dcolumn}
 - \usepackage[flushleft]{threeparttable}
 - \usepackage{booktabs}
 - \def\sym#1{\ifmmode^{#1}\else\(^{#1}\)\fi}

output:
    pdf_document
---

